### ISSUE TITLE
Might be useful to somehow link repos - hpc paralellization & quality check

### ISSUE THREAD

**Issue by kdestasio** [UNFmontreal/Dcm2Bids#25]
Hey,

Thanks for writing your scripts, they've been incredibly useful. 

I wrote some additional scripts that work with yours to (1) run jobs for subjects in parallel in a high performance cluster environment and (2) to check the number of runs for each sequence that end up in BIDS against the expected number and to correct them if possible. I wonder if it might be useful to others to somehow link the repos, if you're interested.

https://github.com/kdestasio/dcm2bids/tree/master/bidsQC

Best,
Krista

**Comment by arnaudbore** [comment]
Dear @kdestasio ,

I know it's been 2 years since you wrote this message without any response. I'm deeply sorry about that.

We are starting a 2021 initiative to push dcm2bids forward.
Please don't hesitate to answer to our survey following this [initiative](https://github.com/UNFmontreal/Dcm2Bids/issues/108)

Have a good day
Arnaud
