### ISSUE TITLE
Enable Choice of Compression Type (pigz w/ dcm2niix hits all cores on shared system)

### ISSUE THREAD

**Issue by bendhouseart** [UNFmontreal/Dcm2Bids#61]
When running dcm2bids on a shared system it hits every core during the compression step, I believe dcm2niix has the optional flag to use the default compression library ala:

```bash
-z : gz compress images (y/i/n/3, default n) [y=pigz, i=internal:miniz, n=no, 3=no,3D]
```

**Comment by neurolabusc** [comment]
It might be nice to have Dcm2Bids allow the user to select the compression. As noted, pigz is a parallel compression that is much faster than single-threaded compression by using all the cores. The benefit is that it is much faster, the downside is that it intentionally leverages all cores available. 

By the way, assuming you are running on Unix (MacOS or Linux) and have pigz 2.3.4 or later the fastest choice is `-z o` which uses pigz in piped-mode - this allows gz files to be created directly rather than saving an uncompressed file first. So if this software is extended to allow control, this would be a nice option.

```
-z : gz compress images (y/o/i/n/3, default n) [y=pigz, o=optimal pigz, i=internal:zlib, n=no, 3=no,3D]
```

**Comment by bendhouseart** [comment]
@cbedetti Hiya, I fixed this some time ago and submitted a pull request. At the time it passed all tests and was ready to merge. It might take some more work now to resolve. 
I was wondering if it would be possible for someone on our team here at DCAN labs to become a contributor to help out with this and some of the other issues posted up? Thanks and please me know, I'd much rather work with you on this branch project than have to maintain a separate fork for our lab.

**Comment by cbedetti** [comment]
Whats wrong with using `dcm2niixOptions` in your config file ?
See : https://cbedetti.github.io/Dcm2Bids/advance/

**Comment by arnaudbore** [comment]
This is already some thing that can be done but need to be explicit in the documentation

**Comment by arnaudbore** [comment]
This has been fixed. Please follow documentation: https://unfmontreal.github.io/Dcm2Bids/docs/how-to/use-advanced-commands/#dcm2niixoptions
