### ISSUE TITLE
pip install dcm2bids error

### ISSUE THREAD

**Issue by alienx-zero** [UNFmontreal/Dcm2Bids#86]
I am following the tutorials. But after installing dcm2bids, dcm2bids --help do not work
here is the error info. 
```(dcm2bids) C:\Users\99488>pip install dcm2bids
Requirement already satisfied: dcm2bids in d:\users\99488\anaconda3\envs\dcm2bids\lib\site-packages (2.1.4)
Requirement already satisfied: future in d:\users\99488\anaconda3\envs\dcm2bids\lib\site-packages (from dcm2bids) (0.18.2)

(dcm2bids) C:\Users\99488>dcm2bids --help
'dcm2bids' is not recognized as an internal or external command,
operable program or batch file.

(dcm2bids) C:\Users\99488>

**Comment by arnaudbore** [comment]
@alienx-zero sorry for the long delay, do you still have this issue ?

**Comment by roeysc** [comment]
I seem to have encountered the same issue. Working on Ubuntu 16.04, I tried installing dcm2bids using `pip install dcm2bids` (both inside and outside of a conda environment), and received the following message:
```
Requirement already satisfied: dcm2bids in ./.local/lib/python3.7/site-packages (2.1.5)
Requirement already satisfied: future>=0.17.1 in ./anaconda3/lib/python3.7/site-packages (from dcm2bids) (0.17.1)
```
Yet  the `dcm2bids` command is not recognized.
Indeed, printing my $PATH in the terminal, I couldn't find dcm2bids there.


What eventually solved the issue was to clond the Dcm2Bids repository and install from there:
```
git clone https://github.com/cbedetti/Dcm2Bids.git
cd Dcm2Bids
pip install --user .
```
I then added `~/.local/bin` directory to my path (in the ~/.bashrc file, add `export PATH="$HOME/.local/bin:$PATH"`, then source this file in the terminal: `source ~/.bashrc`), and now it seems to identify `dcm2bids` properly.

Hope this helps others as well.

Best,
Roey

**Comment by arnaudbore** [comment]
Dear @roeysc,

Can you try this ?

Install venv for python3.7
```
sudo apt-get install python3.7-venv
```

Then
```
python3.7 -m venv env_dcm2bids
source env_dcm2bids/bin/activate
pip install --no-cache-dir dcm2bids
```

You should not have to change anything in your PATH, see here:
```
echo $PATH
/home/bore/env_dcm2bids/bin: (others paths)
```

Can you tell me if it works?

**Comment by roeysc** [comment]
Dear @arnaudbore,
Thanks for you quick and helpful response. It worked perfectly, with one change:

`sudo apt-get install python3.7-venv` gave the following errors:
```
E: Unable to locate package python3.7-venv
E: Couldn’t find any package by glob ‘python3.7-venv’
E: Couldn’t find any package by regexp ‘python3.7-venv’
```
I therefore used `sudo apt-get install python3-venv` instead.

Many thanks,
Roey

**Comment by arnaudbore** [comment]
Dear @roeysc  and @alienx-zero,
Don't hesitate to answer to our survey following our [dcm2bids 2021 initiative](https://github.com/UNFmontreal/Dcm2Bids/issues/108)
Have a good day
